apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: log-stack
spec:
  ports:
  - port: 80
    targetPort: 9898
---
apiVersion: v1
kind: Endpoints
metadata:
  name: grafana-svc
  namespace: log-stack
subsets:
  - addresses:
      - ip: 10.8.77.119
    ports:
      - port: 9898