apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: k3s-apps
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: site
        image: aaronzjc/blog:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 50Mi