apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: k3s-apps
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: blog
    spec:
      volumes:
      - name: site-dir
        emptyDir: {}
      containers:
      - name: blog
        image: aaronzjc/blog:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: site-dir
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
      - name: nginx
        image: nginx
        volumeMounts:
        - name: site-dir
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 50Mi