apiVersion: apps/v1
kind: Deployment
metadata:
  name: mu-commander
  namespace: k3s-apps
spec:
  selector:
    matchLabels:
      app: mu-commander
  replicas: 2
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: mu-commander
    spec:
      volumes:
      - name: mu-conf
        configMap:
          name: mu-config
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: mu-log-dir
        emptyDir: {}
      containers:
      - name: mu-commander
        image: aaronzjc/mu-commander:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: mu-conf
          mountPath: /app/conf
        - name: mu-log-dir
          mountPath: /var/log
        ports:
        - containerPort: 7970
        resources:
          limits:
            cpu: 50m
            memory: 50Mi