apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  namespace: log-stack
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: "/data/loki"