apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-mu-config
  namespace: k3s-apps
data:
  labelMap: |
    {
      "level": "level",
      "host": "pod"
    }
  parser: |
    [PARSER]
      Name        mjson
      Format      json
  fluent-bit-api: |
    [SERVICE]
      Flush        1
      Daemon       Off
      Log_Level    info
      Parsers_File parser.conf
    [INPUT]
      Name          tail
      Path          /var/log/mu.log
      Parser        mjson
      Tag           mu.api
    [Output]
      Name loki
      Match *
      Url http://loki.ops.memosa.cn/loki/api/v1/push
      Buffer true
      DqueSegmentSize 8096
      DqueDir /tmp/flb-storage/buffer
      Labels {app="mu-api"}
      LabelMapPath /fluent-bit/etc/labelMap.json
      DqueName loki.0
  fluent-bit-commander: |
    [SERVICE]
      Flush        1
      Daemon       Off
      Log_Level    info
      Parsers_File parser.conf
    [INPUT]
      Name          tail
      Path          /var/log/mu.log
      Parser        mjson
      Tag           mu.api
    [Output]
      Name loki
      Match *
      Url http://loki.ops.memosa.cn/loki/api/v1/push
      Buffer true
      DqueSegmentSize 8096
      DqueDir /tmp/flb-storage/buffer
      Labels {app="mu-commander"}
      LabelMapPath /fluent-bit/etc/labelMap.json
      DqueName loki.0
