apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-prin-config
  namespace: k3s-apps
data:
  labelMap.json: |
    {
      "level": "level",
      "host": "pod"
    }
  parser.conf: |
    [PARSER]
      Name        mjson
      Format      json
  fluent-bit.conf: |
    [SERVICE]
      Flush        1
      Daemon       Off
      Log_Level    info
      Parsers_File parser.conf
    [INPUT]
      Name          tail
      Path          /var/log/prin.log
      Parser        mjson
      Tag           traefik
    [Output]
      Name loki
      Match *
      Url http://loki.ops.memosa.cn/loki/api/v1/push
      Buffer true
      DqueSegmentSize 8096
      DqueDir /tmp/flb-storage/buffer
      Labels {app="prin"}
      LabelMapPath /fluent-bit/etc/labelMap.json
      DqueName loki.0